### ISSUE TITLE
Elf logic : proxy on shredder parameters

### ISSUE THREAD

**Issue by SamLebarbare** [Xcraft-Inc/xcraft-core-goblin#13]
In this example, i have a `newState` shredder object in parameter of my `updateState(newState)` method :
![image](https://user-images.githubusercontent.com/454255/234674268-69ddefe8-0f21-4215-93ef-0fc6b4dba841.png)

It is possible to have a proxified shredder on it ?

Then i can use newState.shifts insteed of newState.get('shifts')

**Comment by Skywalker13** [comment]
Here the trick:

```js
  /* stateFromGaladriel is received as a Shredder */
  myQuest(stateFromGaladriel) {
    stateFromGaladriel = Elf.Spirit.from(GaladrielState)(stateFromGaladriel);
    /* Now here, you can use magic */
    const {id, name} = stateFromGaladriel;
  }
```

**Comment by Skywalker13** [comment]
I clone because `Elf.Spirit.from` works pretty fine now.
