### ISSUE TITLE
Elfs: helper for create with TTL

### ISSUE THREAD

**Issue by SamLebarbare** [Xcraft-Inc/xcraft-core-goblin#17]
Example of low-level create with TTL :

```
const id = entity.get('id');
      const cmd = `${id.split('@', 1)[0]}.create`;
      const busToken = xBus.getBusTokenFromId(cmd, id);

      quest.createFor(
        'driller.cache-entities',
        `goblin-cache@${busToken}`,
        cmd,
        {
          id,
          desktopId: quest.getSystemDesktop(),
          entity,
          _goblinTTL: ttl || 10000,
        },
        next.parallel()
      );
    });
  ```
  
  Example of helper:
  
  `await new Actor(this).load(10000, desktopId, id, ...someCreateParams);`
  
  load and attach actor to the cache for 10000ms
  
  example of method name:
  
  load -> notion of loading an actor to a feed for an amount of time, notion of cache is hidden
  reload -> generally we reload often for keeping the actor alive and reset the TTL
  mount -> less accurate....
  createForCache -> more precise but less instinctive for the consumer.

**Comment by Skywalker13** [comment]
`retainFor`

**Comment by Skywalker13** [comment]
Sauf erreur t'as implémenté et on peut fermer ?
